app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Dashboard
Route::get('/', ['as' => 'dashboard', 'uses' => function() {
    return view('centaur.dashboard');
}]);
// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Registration
Route::get('register', ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);

// Activation
Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

// Password Reset
Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);

// Users
Route::resource('users', 'UserController');

// Roles
Route::resource('roles', 'RoleController');

//posts
Route::resource('posts', 'PostController');

//homes
Route::resource('homes', 'HomeController');

//comments
Route::resource('comments', 'CommentController');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\model\Post;
use App\model\Comment;
use Sentinel;
use App\Http\Requests;
use Centaur\AuthManager;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Sentinel::check() && Sentinel::inRole('administrator')){
            
            $post = Post::all();
        }elseif (Sentinel::check() && Sentinel::inRole('moderator')){
            
            $post = Post::where('id_user','=', Sentinel::getUser()->id)->get();
        }else{

            $post = Post::all();
        }

        return view('Centaur::homes.index')->with('post', $post);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findorfail($id);     
        $comments = Comment::where('id_post','=',$id)->get();

        return view('Centaur::homes.home')->with('post',$post)->with('comments',$comments);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $comment = Post::where('id','=',$id)->delete();
         return redirect('/')->with('message','Success .. ')
                                        ->with('alert','success');
    }
}

resources/views/centaur/homes/home.blade.php
@extends('Centaur::layout')

@section('title', 'Home')

@section('content')
<div class="row">
  <div class="panel panel-info">
    <div class="panel-body">
      <h1>{{$post->title}}</h1>
      <p align="right"><i>
      Date: {{$post->created_at}}
      </i></p>
      <hr>
        <br>
          <p>
            <img src='/uploads/artikel/{{ $post->image }}' height="400" width="500px" alt="">
          </p>
          <p>
            {!!$post->content!!}
          </p>
          <p>
            Create by: <strong><b>{{$post->user->first_name}}</b></strong>
          </p>
          <p>
            E-mail: <strong><b>{{$post->user->email}}</b></strong>
          </p>
      </div>
    </div>

    @if (count($comments)>0)
    <div class="panel panel-default">
      <div class="panel-body">
        <h2>Commented : </h2>
        <br>
          @foreach ($comments as $comment)
            @if (Sentinel::check())
              <div class="pull-right">
                <form action="{{ route('comments.destroy',$comment->id) }}" method="POST">
                  {!! csrf_field() !!}
                  {!! method_field('DELETE') !!}
                  <input type="hidden" name="post_id" value="{{$comment->post_id}}">
                  <button class="btn btn-danger" title="DELETE"><i class="fa fa-close"></i></button>
                </form>
              </div>
             @endif
              <h4><strong>{{$comment->name}}</strong></h4>        
              <p>
                {{$comment->comment}}
              </p>
              <hr>
          @endforeach
      </div>
    </div>
    @endif
   
    <div class="panel panel-default">
      <div class="panel-body">
        <form action="{{route('comments.store')}}" method="POST" role="form">
          {{csrf_field()}}
            <h2>Comment a post</h2>
              <input type="hidden" name="id_post" value="{{$post->id}}">

                <div class="row">
                  <div class="form-group has-info col-md-3">
                    <label for="title">Name</label>
                    <input type="text" class="form-control" name="name" id="title" placeholder="Place Your Name Here">
                  </div>
                </div>

                <div class="row">
                  <div class="form-group has-info col-md-3">
                    <label for="title">E-mail</label>
                    <input type="email" class="form-control" name="email" id="title" placeholder="@example.com">
                  </div>
                </div>

                <div class="row">
                  <div class="form-group has-info col-md-6">
                  <label for="content">Comment</label>
                  <textarea id="content" rows="4" name="comment" placeholder="Place Your Comment Here" class="form-control"></textarea>
                  </div>
                </div> 

          <button type="submit" class="btn btn-info btn-raised">Submit</button>
        </form>
      </div>
    </div>    
  </div>
@stop

resources/views/centaur/homes/index.blade.php
@extends('Centaur::layout')

@section('title', 'Home')

@section('content')
@if($post->count())
@foreach ($post as $data)
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-default">
      <div class="panel-body">
      @if (Sentinel::check())
        <div class="pull-right">
          <form action="{{ url('posts',$data->id) }}" method="POST">
            {!! csrf_field() !!}
            {!! method_field('DELETE') !!}
              <button class="btn btn-danger" title="DELETE"><i class="fa fa-close"></i></button>
          </form>
         </div>
      @endif
          <h3>
            <a href="{{ route('homes.show', $data->id) }}" title="">{{str_limit($data->title,20)}}</a>
            </h3><br>
          <p>
            <img src='/uploads/artikel/{{ $data->image }}' height="200" width="200px" alt="">
          </p><br>
          <p>{!!str_limit($data->content,100)!!}
            <a href="{{ route('homes.show', $data->id) }}" title="">Read more</a>
          </p>
      </div>
    </div>        
  </div>
@endforeach
@else
    <div class="row">
      <div class="col-lg-12">
      <div class="jumbotron">
            <h1>Nothing Article's!</h1>
            <p>you have a create new article :)</p>
        </div>
      </div>
    </div>
@endif
@stop